build / deploy check
Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,23 @@
-name: Build_Check
+#
+# build.yml - GitHub build action for OpenHantek6022
+# Copyright (C) 2023- openhantek
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+
+
+name: Build
 # check if OH6022 builds on some recent operating systems
 # deploy Ubuntu / macOS / Windows binaries
 
@@ -10,32 +29,36 @@ env:
   BUILD_TYPE: Release
 
 
+# jobs:
+#   build_check:
+#     strategy:
+#       # do not stop on 1st fail
+#       fail-fast: false
+#       matrix:
+#         # GitHub runner macos build is broken: https://github.com/actions/runner-images/issues/577
+#         #   Could not symlink bin/2to3-3.11 Target /usr/local/bin/2to3-3.11 already exists.
+#         #   Could not symlink bin/2to3 Target /usr/local/bin/2to3 already exists.
+#         # hack fix: https://github.com/actions/setup-python/issues/577#issuecomment-1365231822
+#         os: [ubuntu-22.04, macos-12, windows-2022]
+#
+#     runs-on: ${{ matrix.os }}
+#
+#
+#     steps:
+
+
 jobs:
-  build_check:
-    strategy:
-      # do not stop on 1st fail
-      fail-fast: false
-      matrix:
-        # GitHub runner macos build is broken: https://github.com/actions/runner-images/issues/577
-        #   Could not symlink bin/2to3-3.11 Target /usr/local/bin/2to3-3.11 already exists.
-        #   Could not symlink bin/2to3 Target /usr/local/bin/2to3 already exists.
-        # hack fix: https://github.com/actions/setup-python/issues/577#issuecomment-1365231822
-        os: [ubuntu-22.04, macos-12, windows-2022]
 
-    runs-on: ${{ matrix.os }}
-
-
+  # --- Linux (Ubuntu) steps ---
+  linux-x86_64:
+    runs-on: ubuntu-latest
     steps:
 
-
     # --- Clone the latest commit ---
-
     - name: Checkout
       uses: actions/checkout@v3
 
-
     # --- Config git and get the version from "git describe" ---
-
     - name: Config Git
       id: config_git
       shell: bash
@@ -47,9 +70,6 @@ jobs:
         echo "git_describe=$(git describe)"
         echo "git_describe=$(git describe)" >> $GITHUB_OUTPUT
 
-
-    # --- Linux (Ubuntu) steps ---
-
     - name: Install Ubuntu Build Requirements
       if: startsWith(matrix.os, 'ubuntu')
       run: |
@@ -58,7 +78,6 @@ jobs:
         sudo apt -y upgrade
         sudo apt install g++ make cmake fakeroot rpm qttools5-dev libfftw3-dev binutils-dev \
           libusb-1.0-0-dev libqt5opengl5-dev mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev
-
 
     - name: Ubuntu Build
       # GitHub hosts Linux runners on Standard_DS2_v2 virtual machines in Microsoft Azure:
@@ -72,7 +91,6 @@ jobs:
         fakeroot make -j8 package
         ls -l packages
 
-
     - name: Upload Ubuntu Artifacts
       # *.deb *.rpm *.tgz
       if: startsWith(matrix.os, 'ubuntu')
@@ -82,10 +100,28 @@ jobs:
         path: ${{github.workspace}}/build/packages/*
 
 
-    # --- macOS steps ---
+  # --- macOS steps ---
+  macos-x86_64:
+    runs-on: macos-latest
+    steps:
+
+    # --- Clone the latest commit ---
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    # --- Config git and get the version from "git describe" ---
+    - name: Config Git
+      id: config_git
+      shell: bash
+      run: |
+        git config user.email "Ho-Ro@users.noreply.github.com"
+        git config user.name "Ho-Ro"
+        git fetch --prune --unshallow --tags || true
+        git submodule update --init --recursive
+        echo "git_describe=$(git describe)"
+        echo "git_describe=$(git describe)" >> $GITHUB_OUTPUT
 
     - name: Install macOS Build Requirements
-      if: startsWith(matrix.os, 'macos')
       run: |
         mkdir build
         brew update
@@ -96,12 +132,10 @@ jobs:
         ln -sf /usr/local/opt/gcc/lib/gcc/11/libgcc_s.1.1.dylib \
           /usr/local/opt/qt5/lib/libgcc_s.1.1.dylib.framework/libgcc_s.1.1.dylib
 
-
     - name: macOS Build
       # GitHub hosts macOS runners in GitHub's own macOS Cloud:
       # 3-core CPU, 14 GB of RAM memory, 14 GB of SSD disk space
       working-directory: ${{github.workspace}}/build
-      if: startsWith(matrix.os, 'macos')
       run: |
         cp ../CHANGELOG changelog
         cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
@@ -132,16 +166,33 @@ jobs:
           true
         fi
 
-
     - name: Upload macOS Artifacts
-      if: startsWith(matrix.os, 'macos')
       uses: actions/upload-artifact@v3
       with:
         name: openhantek_${{ steps.config_git.outputs.git_describe }}_osx_x86_64
         path: ${{github.workspace}}/build/packages/*
 
 
-    # --- Windows steps ---
+  # --- Windows steps ---
+  windows-mingw_w64:
+    runs-on: windows-2022
+    steps:
+
+    # --- Clone the latest commit ---
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    # --- Config git and get the version from "git describe" ---
+    - name: Config Git
+      id: config_git
+      shell: bash
+      run: |
+        git config user.email "Ho-Ro@users.noreply.github.com"
+        git config user.name "Ho-Ro"
+        git fetch --prune --unshallow --tags || true
+        git submodule update --init --recursive
+        echo "git_describe=$(git describe)"
+        echo "git_describe=$(git describe)" >> $GITHUB_OUTPUT
 
     - name: Install MSYS2 Packages
       if: startsWith(matrix.os, 'windows')
@@ -180,18 +231,18 @@ jobs:
       if: startsWith(matrix.os, 'windows')
       uses: actions/upload-artifact@v3
       with:
-        name: openhantek_${{ steps.config_git.outputs.git_describe }}_win_x64
+        name: openhantek_${{ steps.config_git.outputs.git_describe }}_mingw_w64
         path: ./build/packages/*.zip
 
 
-    # --- Tagged Commit -> Upload Release ---
-
-    - name: Upload Linux / macOS / Windows Release Assets
-      if: startsWith(github.ref, 'refs/tags/')
-      uses: softprops/action-gh-release@v1
-      with:
-        prerelease: true
-        files: ./build/packages/*
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    # # --- Tagged Commit -> Upload Release ---
+    #
+    # - name: Upload Linux / macOS / Windows Release Assets
+    #   if: startsWith(github.ref, 'refs/tags/')
+    #   uses: softprops/action-gh-release@v1
+    #   with:
+    #     prerelease: true
+    #     files: ./build/packages/*
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
